version: '3.9'

services:
  backend:
    build: ./backend
    expose:
      - "8000"
    image: uthra02/student-feedback-backend:latest
    volumes:
      - ./backend:/app
    networks:
      - app_net
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: uthra02/student-feedback-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app_net
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app_net
    restart: unless-stopped
  autoscaler:
    build:
      context: ./autoscaler
      dockerfile: Dockerfile.autoscaler
    image: uthra02/student-feedback-autoscaler:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scaling_log.txt:/app/scaling_log.txt  # ✅ Add this line
    depends_on:
      - backend
    networks:
      - app_net
    restart: unless-stopped

  monitor:
    build: ./monitoring
    ports:
      - "5000:5000"
    volumes:
      - ./monitoring/scaling_log.txt:/app/scaling_log.txt 
    networks:
      - app_net
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
